// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQhC_1L0hMJltzgtCUsblGk5grqS7HIZ0',
    appId: '1:286219943559:web:6bdeb85df7234dc9788222',
    messagingSenderId: '286219943559',
    projectId: 'starbook-clone-6dbe1',
    authDomain: 'starbook-clone-6dbe1.firebaseapp.com',
    storageBucket: 'starbook-clone-6dbe1.firebasestorage.app',
    measurementId: 'G-LBGGLVX838',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4zcf_YEDzMULpBfGbGmgNNyvi3SZgBg',
    appId: '1:286219943559:android:7359cb44ef80436b788222',
    messagingSenderId: '286219943559',
    projectId: 'starbook-clone-6dbe1',
    storageBucket: 'starbook-clone-6dbe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKohO12-hicKz3tkTF7i_5MtW1k5vT7mk',
    appId: '1:286219943559:ios:198f0cbb27344d05788222',
    messagingSenderId: '286219943559',
    projectId: 'starbook-clone-6dbe1',
    storageBucket: 'starbook-clone-6dbe1.firebasestorage.app',
    iosBundleId: 'com.example.starBookRefactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKohO12-hicKz3tkTF7i_5MtW1k5vT7mk',
    appId: '1:286219943559:ios:198f0cbb27344d05788222',
    messagingSenderId: '286219943559',
    projectId: 'starbook-clone-6dbe1',
    storageBucket: 'starbook-clone-6dbe1.firebasestorage.app',
    iosBundleId: 'com.example.starBookRefactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQhC_1L0hMJltzgtCUsblGk5grqS7HIZ0',
    appId: '1:286219943559:web:4ad152fe38123a92788222',
    messagingSenderId: '286219943559',
    projectId: 'starbook-clone-6dbe1',
    authDomain: 'starbook-clone-6dbe1.firebaseapp.com',
    storageBucket: 'starbook-clone-6dbe1.firebasestorage.app',
    measurementId: 'G-QQZ1WHSX3F',
  );
}
